### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kgryte** [compute-io/array-dtype#2]
Small module providing an interface in front of a list of `array` data types. As the data types are listed in a separate file, can be `required` independent of interface. Will be used in `matrix` and probably `ndarray` when, e.g., casting from one `dtype` to another `dtype`.

Complementary module to [compute-array-constructors](https://github.com/compute-io/array-constructors).

**Comment by Planeshifter** [comment]
Did one small fix concerning the documentation, module ready to be published.

**Comment by kgryte** [comment]
Awesome. Thanks!

**Comment by kgryte** [comment]
Done.
